### ISSUE TITLE
Differences between tun interfaces and tap interfaces

### ISSUE THREAD

**Issue by myonlystarWang** [s5uishida/change_from_tun_to_tap_in_open5gs#1]
Hi @s5uishida ,
    Thank you for the lots of work you have done to help us better understand the 4G/5G system.
    I want to ask the differences between tun interfaces and tap interfaces.
    It seems that performance will be higher if you use the tap interface, right?Have you done a comparison test of tap and tun?
    Thanks in advance!

**Comment by s5uishida** [comment]
@myonlystarWang 

I haven't done anything other than what I wrote as follows.

https://github.com/s5uishida/simple_measurement_of_upf_performance

**Comment by myonlystarWang** [comment]
> @myonlystarWang
> 
> I haven't done anything other than what I wrote as follows.
> 
> https://github.com/s5uishida/simple_measurement_of_upf_performance

Thank you so much for that information!
